// <auto-generated />
using System;
using HastaneAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HastaneAPI.Model.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HastaneId")
                        .HasColumnType("int");

                    b.Property<string>("Klinik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MuayeneTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HastaneId");

                    b.ToTable("Hastalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adi = "Ahmet",
                            HastaneId = 1,
                            Klinik = "Dis",
                            MuayeneTarihi = new DateTime(2024, 2, 6, 23, 15, 59, 167, DateTimeKind.Local).AddTicks(6343),
                            Soyadi = "Yilmaz"
                        },
                        new
                        {
                            Id = 2,
                            Adi = "Mehmet",
                            HastaneId = 2,
                            Klinik = "KBB",
                            MuayeneTarihi = new DateTime(2024, 2, 6, 23, 15, 59, 167, DateTimeKind.Local).AddTicks(6345),
                            Soyadi = "Yilacak"
                        },
                        new
                        {
                            Id = 3,
                            Adi = "Ali",
                            HastaneId = 1,
                            Klinik = "Goz",
                            MuayeneTarihi = new DateTime(2024, 2, 6, 23, 15, 59, 167, DateTimeKind.Local).AddTicks(6347),
                            Soyadi = "Yildi"
                        });
                });

            modelBuilder.Entity("HastaneAPI.Model.Hastane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaneAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hastaneler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "Bagcilar",
                            HastaneAdi = "Medipol"
                        },
                        new
                        {
                            Id = 2,
                            Adres = "Kadikoy",
                            HastaneAdi = "Acibadem"
                        });
                });

            modelBuilder.Entity("HastaneAPI.Model.Hasta", b =>
                {
                    b.HasOne("HastaneAPI.Model.Hastane", "Hastane")
                        .WithMany("Hastalar")
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hastane");
                });

            modelBuilder.Entity("HastaneAPI.Model.Hastane", b =>
                {
                    b.Navigation("Hastalar");
                });
#pragma warning restore 612, 618
        }
    }
}
